# Generated by Django 5.0.3 on 2024-03-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0005_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
