# Generated by Django 5.0.3 on 2024-03-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0006_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('', 'Please Choose a Topic That Interests You'), ('Meetings', 'Meetings and Joint Activities'), ('Event', 'Event Overview and Organizational Issues'), ('Cinema', 'Going to the Cinema'), ('Suggestions', 'Suggestions for Club Activities'), ('Introduction', 'New Members Introduction'), ('Discussions', 'General Discussions (Off Topic)'), ('Testing', 'Testing Environment')], default='', max_length=255),
        ),
    ]
