# Generated by Django 5.0.3 on 2024-03-20 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('', '-- Please choose --'), ('Join', 'For those who want to join the club'), ('Events', 'Official club events and organisational matters'), ('Suggestions', 'Suggestions, complaints for club activities'), ('merchandise', 'Club merchandise'), ('Other', "Other general issues related to the club's activities")], default='', max_length=100, verbose_name='subject')),
                ('content', models.TextField(blank=True, default='', max_length=15000, verbose_name='content')),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='full name')),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='sent at')),
                ('mail_sent', models.BooleanField(default=False, verbose_name='email sent')),
                ('status', models.CharField(choices=[('new', 'new'), ('read', 'read'), ('processing', 'processing'), ('closed', 'closed')], db_index=True, default='new', max_length=15, verbose_name='status')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'ordering': ['-sent_at'],
            },
        ),
    ]
