# Generated by Django 5.0.3 on 2024-03-23 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_ticket_options_alter_ticketmessage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-sent_at'], 'verbose_name': 'ticket', 'verbose_name_plural': 'tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ['-sent_at'], 'verbose_name': 'ticket message', 'verbose_name_plural': 'ticket messages'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='content',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='mail_sent',
            field=models.BooleanField(default=False, verbose_name='email sent'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='sender'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sender_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sender_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='sent at'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('read', 'read'), ('processing', 'processing'), ('closed', 'closed')], db_index=True, default='new', max_length=15, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(choices=[('', '-- Please choose --'), ('Join', 'For those who want to join the club'), ('Events', 'Official club events and organisational matters'), ('Suggestions', 'Suggestions, complaints for club activities'), ('merchandise', 'Club merchandise'), ('Other', "Other general issues related to the club's activities")], default='', max_length=50, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='content',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='is read'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='mail_sent',
            field=models.BooleanField(default=False, verbose_name='email sent'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_ticket_messages', to=settings.AUTH_USER_MODEL, verbose_name='recipient'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='recipient_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='recipient_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_ticket_messages', to=settings.AUTH_USER_MODEL, verbose_name='sender'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='sender_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='sender_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='sent at'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ticket', verbose_name='ticket'),
        ),
    ]
