# Generated by Django 5.0.3 on 2024-03-27 12:44

import django.db.models.deletion
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_ticket_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmessage',
            name='content',
        ),
        migrations.AddField(
            model_name='ticket',
            name='access_key',
            field=models.CharField(default=website.models.get_access_key, max_length=42, verbose_name='access key'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='body',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='website.ticket', verbose_name='ticket'),
        ),
    ]
