# Generated by Django 5.0.3 on 2024-03-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_ticketmessage_content_ticket_access_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmessage',
            name='body',
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='content',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='content'),
        ),
    ]
