# Generated by Django 5.0.3 on 2024-04-03 21:27

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_ticketmessage_body_ticketmessage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/events/', verbose_name='event image')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('content', tinymce.models.HTMLField(verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                ('cancellation_date', models.DateField(blank=True, null=True, verbose_name='cancellation date')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
