# Generated by Django 5.0.3 on 2024-04-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/merchandise/', verbose_name='image')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='title')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'merchandise',
                'verbose_name_plural': 'merchandises',
            },
        ),
    ]
