# Generated by Django 5.0.3 on 2024-04-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_merchandise_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(choices=[('', 'Prašome Pasirinkti Temą, Kuri Jus Domina'), ('Join', 'For Those Wishing to Become Club Members'), ('Events', 'Official Club Events and Organizational Matters'), ('Suggestions', 'Suggestions, Requests for Club Activities'), ('Merchandise', 'Club Merchandise'), ('Other', 'Other General Issues Related to Club Activities')], default='', max_length=50, verbose_name='subject'),
        ),
    ]
