# Generated by Django 5.0.3 on 2024-04-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_ticket_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(choices=[('', 'Please Choose a Topic That Interests You'), ('Join', 'For Those Wishing to Become Club Members'), ('Events', 'Official Club Events and Organizational Matters'), ('Suggestions', 'Suggestions, Requests for Club Activities'), ('Merchandise', 'Club Merchandise'), ('Other', 'Other General Issues Related to Club Activities')], default='', max_length=50, verbose_name='subject'),
        ),
    ]
