# Generated by Django 5.0.3 on 2024-04-14 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_ticket_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date'], 'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
    ]
